version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka-1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  producer:
    build: producer/
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    depends_on:
      - kafka

  no-retry-consumer:
    build: consumer/
    environment:
      MAIN_CLASS: "com.sample.NoRetryConsumer"
      PERCENTAGE_FAILURES: 10
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_MAX_POLL_RECORDS: 20
      KAFKA_MAX_POLL_INTERVAL_MS: 10000
    depends_on:
      - kafka

  limited-retries-consumer:
    build: consumer/
    environment:
      MAIN_CLASS: "com.sample.LimitedRetriesConsumer"
      PERCENTAGE_FAILURES: 10
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_MAX_POLL_RECORDS: 20
      KAFKA_MAX_POLL_INTERVAL_MS: 10000
    depends_on:
      - kafka

  infinite-retries-consumer:
    build: consumer/
    environment:
      MAIN_CLASS: "com.sample.InfiniteRetriesConsumer"
      PERCENTAGE_FAILURES: 10
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_MAX_POLL_RECORDS: 10
      KAFKA_MAX_POLL_INTERVAL_MS: 10000
    depends_on:
      - kafka